# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  # Name the workflow "welcome"
  build:
    docker:
      - image: jupyter/base-notebook:latest
    # Run the welcome/run job in its own container
    steps:
      - checkout
      - run: ./convert.sh >> docs/index.html
  deploy:
    docker:
      - image jupyter/base-notebook:latest
    # Run the welcome/run job in its own container
    steps:
      - checkout
      - run: ./convert.sh >> html/index.html
      - run: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master