# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  # Name the workflow "welcome"
  build:
    docker:
      - image: marufeuille/pages-building-image:latest
    # Run the welcome/run job in its own container
    steps:
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tUser git\n" > ~/.ssh/config
      - run: git clone -q git@github.com:marufeuille/my-notebooks.git
      - run: ./my-notebooks/convert.sh
  deploy:
    docker:
      - image: marufeuille/pages-building-image:latest
    # Run the welcome/run job in its own container
    steps:

      - add_ssh_keys:
          fingerprints:
            - "67:80:fa:3a:81:5c:f2:e1:89:b7:57:1d:7f:62:45:2a"
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n\tUser git\n" > ~/.ssh/config
      - run: git clone -q git@github.com:marufeuille/my-notebooks.git
      - run: ./my-notebooks/convert.sh
      - run: ./my-notebooks/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
